#!/bin/bash -l
#SBATCH -D /home/dgold/BLAST
#SBATCH --mail-type=ALL
#SBATCH --mail-user=dgold@ucdavis.edu 
#SBATCH -o /home/dgold/IQTREE-o%j.txt
#SBATCH -e /home/dgold/IQTREE-e%j.txt
#SBATCH -J IQTREE
#SBATCH -t 12:00:00 
cd /home/dgold/sirtuins
PATH=$PATH:/home/dgold/.linuxbrew/bin:/home/dgold/miniconda3/bin
iqtree -s 8_SIR2_Domains.mafft.fasta -m MFP -bb 1000 -nt 16
